name: iProtectorPortals
main: iProtectorPortals\Main
version: 1.0.0
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
author: MCPEPIG
depend: iProtector

permissions:
 portal:
  default: op
  description: "Allows using all iProtectorPortal features" 
  children:
    portal.use:
      default: true
      description: "Allow using all iProtectorPortals"
    portal.command:
      default: op
      description: "Allow using all iProtectorPortal commands"
      children:
        portal.command.portal:
          default: op
          description: "Allow using /portal"
